name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '21 4 * * 0,3,5'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto_renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          YD_EMAIL: ${{ secrets.YD_EMAIL }}
          YD_APP_PWD: ${{ secrets.YD_APP_PWD }}
          USERID: ${{ secrets.USERID }}
          APIKEY: ${{ secrets.APIKEY }}
        run: python main.py
